import '@/styles/_globals.scss';

import React from 'react';
import clsx from 'clsx';
import { Inter } from 'next/font/google';
import RootLayout from '@/components/RootLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full bg-neutral-950 text-base antialiased">
      <body className={clsx('flex min-h-full flex-col', inter.className)}>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
